import { StyleSheet } from "react-native";

export const C = {
  ground: "#111417",
  surface: "#1b2226",
  border: "#314047",
  text: "#eeebf2",
  muted: "#9ba8ad",
  accent: "#2fbf8f",
  amber: "#f6b44b",
  danger: "#e5484d",
};

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: C.ground },
  header: { paddingHorizontal: 16, paddingTop: 8, paddingBottom: 12 },
  eyebrow: {
    color: C.accent,
    fontSize: 10,
    letterSpacing: 0,
    textTransform: "uppercase",
    marginBottom: 4,
  },
  title: { color: C.text, fontSize: 22, fontWeight: "700", letterSpacing: 0 },
  snapshot: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 12 },
  pill: {
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
    backgroundColor: C.surface,
  },
  pillLabel: { color: C.muted, fontSize: 11, marginBottom: 2 },
  pillValue: { color: C.text, fontSize: 14, fontWeight: "700" },
  list: { flex: 1, paddingHorizontal: 16 },
  empty: { color: C.muted, paddingVertical: 24, fontSize: 14, lineHeight: 21 },

  // Full-screen avatar layout: the video is an absolute-fill background;
  // everything else sits in a translucent panel pinned to the bottom so the
  // video stays the dominant visual, not a small box competing with a
  // regular scrolling screen.
  fullScreenRoot: { flex: 1, backgroundColor: C.ground },
  overlayRoot: { flex: 1 },
  overlayTopBar: { paddingHorizontal: 12, paddingTop: 8 },
  bottomPanel: {
    backgroundColor: "rgba(17,20,23,0.9)",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderTopWidth: 1,
    borderColor: C.border,
    paddingTop: 10,
    paddingHorizontal: 16,
    maxHeight: "45%",
  },
  compactHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    marginBottom: 6,
  },
  compactHeaderTitle: { color: C.text, fontSize: 15, fontWeight: "700", flexShrink: 1 },
  compactHeaderMeta: { color: C.muted, fontSize: 12 },
  transcriptList: { maxHeight: 200, flexGrow: 0 },

  presenceBadge: {
    alignSelf: "flex-start",
    marginLeft: 12,
    backgroundColor: "rgba(17,20,23,0.75)",
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  presenceBadgeText: { color: C.text, fontSize: 13, fontWeight: "600" },
presencePreview: {
    position: "absolute",
    bottom: 24,
    right: 16,
    width: 110,
    height: 150,
    borderRadius: 14,
    overflow: "hidden",
    borderWidth: 2,
    borderColor: C.border,
    backgroundColor: "#000",
  },  
  statusBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginHorizontal: 16,
    marginBottom: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: C.border,
    backgroundColor: C.surface,
  },
  statusDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: C.muted },
  statusDotOk: { backgroundColor: C.accent },
  statusDotBad: { backgroundColor: C.danger },
  statusText: { color: C.muted, fontSize: 12, flex: 1 },
  statusRetryText: { color: C.accent, fontSize: 12, fontWeight: "700" },

  bubble: { marginVertical: 5, padding: 11, borderRadius: 10, maxWidth: "88%" },
  bubbleUser: { alignSelf: "flex-end", backgroundColor: C.accent },
  bubbleAgent: {
    alignSelf: "flex-start",
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.border,
  },
  bubbleTextUser: { color: "#fff", fontSize: 15, lineHeight: 21 },
  bubbleTextAgent: { color: C.text, fontSize: 15, lineHeight: 21 },

  gate: {
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.border,
    borderLeftWidth: 3,
    borderLeftColor: C.accent,
    borderRadius: 8,
    padding: 12,
    marginVertical: 6,
  },
  gateTitle: { color: C.text, fontSize: 15, fontWeight: "600", marginBottom: 4 },
  gateBody: { color: C.muted, fontSize: 13, lineHeight: 19 },
  gateDone: { color: C.muted, fontSize: 13, fontStyle: "italic" },
  gateRow: { flexDirection: "row", gap: 8, marginTop: 12 },
  card: {
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 8,
    padding: 12,
    marginVertical: 6,
  },
  cardTitle: { color: C.text, fontSize: 15, fontWeight: "700", marginBottom: 8 },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    paddingVertical: 6,
  },
  rowStack: { flex: 1 },
  rowLabel: { color: C.text, fontSize: 14, flexShrink: 1 },
  rowMeta: { color: C.muted, fontSize: 12, marginTop: 2 },
  rowValue: { color: C.text, fontSize: 14, fontWeight: "700" },
  rowDivider: { borderTopWidth: 1, borderTopColor: C.border },
  chipRow: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginTop: 4 },
  chip: {
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 4,
    backgroundColor: C.ground,
  },
  chipText: { color: C.text, fontSize: 12 },
  budgetRow: { marginBottom: 8 },
  meter: {
    height: 6,
    borderRadius: 6,
    backgroundColor: "#253037",
    overflow: "hidden",
  },
  meterFill: { height: 6, borderRadius: 6, backgroundColor: C.amber },

  btn: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: C.border,
  },
  btnText: { color: C.text, fontSize: 14 },
  btnPrimary: { backgroundColor: C.accent, borderColor: C.accent },
  btnPrimaryText: { color: "#fff", fontSize: 14, fontWeight: "600" },
  btnDisabled: { opacity: 0.45 },
  btnDisabledText: { color: C.muted },

  centerScreen: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
    gap: 8,
  },
  scrollScreen: {
    flexGrow: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  responsiveColumn: {
    width: "100%",
    maxWidth: 480,
    alignItems: "center",
    gap: 8,
  },
  responsiveRow: {
    width: "100%",
    maxWidth: 760,
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "center",
    gap: 32,
  },
  responsiveRowCol: {
    flex: 1,
    alignItems: "center",
    gap: 8,
  },
  brandTitle: { color: C.text, fontSize: 30, fontWeight: "800" },
  brandTagline: { color: C.muted, fontSize: 14, textAlign: "center" },

  errorText: { color: C.danger, fontSize: 13, textAlign: "center", marginTop: 4 },

  profileCard: {
    width: "100%",
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 12,
    padding: 16,
    alignItems: "center",
    gap: 4,
    marginTop: 24,
  },
  avatar: { width: 64, height: 64, borderRadius: 32, marginBottom: 8, backgroundColor: C.border },
  profileName: { color: C.text, fontSize: 18, fontWeight: "700" },
  profileEmail: { color: C.muted, fontSize: 13 },

  btnBlock: { width: "100%", alignItems: "center" },
  btnLink: { color: C.muted, fontSize: 13, marginTop: 16 },

  composer: {
    flexDirection: "row",
    gap: 8,
    padding: 12,
    borderTopWidth: 1,
    borderTopColor: C.border,
  },
  input: {
    flex: 1,
    backgroundColor: C.surface,
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: C.text,
    fontSize: 15,
  },
});
